plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto --exclude /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/Exclude-ADNI_cluster_01_forward_757LONI_12_auto-HRC.txt --make-bed --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/TEMP1
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/TEMP1 --update-map /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/Chromosome-ADNI_cluster_01_forward_757LONI_12_auto-HRC.txt --update-chr --make-bed --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/TEMP2
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/TEMP2 --update-map /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/Position-ADNI_cluster_01_forward_757LONI_12_auto-HRC.txt --make-bed --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/TEMP3
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/TEMP3 --flip /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/Strand-Flip-ADNI_cluster_01_forward_757LONI_12_auto-HRC.txt --make-bed --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/TEMP4
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/TEMP4 --a2-allele /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/Force-Allele1-ADNI_cluster_01_forward_757LONI_12_auto-HRC.txt --make-bed --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 1 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr1
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 1 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr1
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 2 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr2
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 2 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr2
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 3 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr3
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 3 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr3
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 4 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr4
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 4 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr4
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 5 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr5
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 5 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr5
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 6 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr6
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 6 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr6
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 7 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr7
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 7 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr7
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 8 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr8
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 8 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr8
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 9 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr9
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 9 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr9
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 10 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr10
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 10 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr10
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 11 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr11
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 11 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr11
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 12 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr12
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 12 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr12
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 13 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr13
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 13 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr13
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 14 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr14
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 14 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr14
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 15 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr15
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 15 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr15
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 16 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr16
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 16 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr16
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 17 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr17
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 17 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr17
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 18 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr18
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 18 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr18
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 19 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr19
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 19 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr19
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 20 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr20
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 20 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr20
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 21 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr21
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 21 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr21
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --make-bed --chr 22 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr22
plink2 --bfile /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated --real-ref-alleles --recode vcf --chr 22 --out /Users/taehyo/Library/CloudStorage/Dropbox/NYU/Research/Research/Data/data_l0ipls/GWAS/taehyo/data/ADNI_1/ADNI_cluster_01_forward_757LONI_12_auto-updated-chr22
rm TEMP*
